export const ADD_PAINTINGS = "ADD_PAINTINGS";
export const PAINT_LOADING = "PAINT_LOADING";
export const PAINT_FAILED = "PAINT_FALIED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";